"""
sweep_b2.py — Sequential curvature sweep for Experiment B2 (float64 probe)
===========================================================================

Runs B2 configs in order: k10 → k20 → k50 → (k100 with --all).

After each run:
  - b2_k10: replication check vs Experiment B k10 baseline (283.7 PPL).
    Warns and pauses if diff > 2.0. Use --force to skip the check.
  - b2_k20+: stops sweep if PPL degrades > 3.0 PPL vs the previous run.

Usage:
    cd ~/hyper-attn-nano
    source activate.sh
    python scripts/sweep_b2.py            # k10 → k20 → k50
    python scripts/sweep_b2.py --all      # also runs k100
    python scripts/sweep_b2.py --force    # skips replication check warning
"""

import argparse
import json
import math
import os
import subprocess
import sys

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SWEEP_BASE = [
    ("exp_b2_k10", "configs/nano_b2_k10.yaml",  -10.0),
    ("exp_b2_k20", "configs/nano_b2_k20.yaml",  -20.0),
    ("exp_b2_k50", "configs/nano_b2_k50.yaml",  -50.0),
]
SWEEP_ALL = SWEEP_BASE + [
    ("exp_b2_k100", "configs/nano_b2_k100.yaml", -100.0),
]

RESULTS_LOG_DIR = "results/logs/exp_b2"
SUMMARY_PATH    = "results/exp_b2_summary.md"

# Replication baseline from Experiment B k10
B_K10_BASELINE_PPL  = 283.7
REPLICATION_TOL_PPL = 2.0

# Stop sweep if PPL degrades more than this vs previous step
DEGRADATION_TOL_PPL = 3.0


# ---------------------------------------------------------------------------
# Log helpers (same pattern as sweep_curvature.py)
# ---------------------------------------------------------------------------

def _get_final_ppl(run_id: str) -> float | None:
    log_path = os.path.join(RESULTS_LOG_DIR, f"{run_id}_train.jsonl")
    if not os.path.exists(log_path):
        return None
    records = []
    with open(log_path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    for rec in reversed(records):
        ppl = rec.get("val_ppl")
        if ppl is not None and math.isfinite(ppl):
            return ppl
    return None


def _detect_divergence(run_id: str):
    log_path = os.path.join(RESULTS_LOG_DIR, f"{run_id}_train.jsonl")
    if not os.path.exists(log_path):
        raise FileNotFoundError(
            f"Log file not found: {log_path}\n"
            f"  Check that the config run_id matches '{run_id}' "
            f"and that train.py completed without error."
        )
    records = []
    with open(log_path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    if not records:
        raise RuntimeError(
            f"Log file exists but has no valid records: {log_path}"
        )
    div_step = None
    for rec in records:
        ppl = rec.get("val_ppl", float("inf"))
        if not math.isfinite(ppl) or ppl > 1e6:
            if div_step is None:
                div_step = rec["step"]

    final_rec  = records[-1]
    final_step = final_rec["step"]
    if div_step is not None and div_step >= final_step:
        return "DIVERGED", div_step
    elif div_step is not None:
        return "DEGRADED", div_step
    else:
        return "STABLE", None


# ---------------------------------------------------------------------------
# Summary writer
# ---------------------------------------------------------------------------

def _write_summary(results: list):
    os.makedirs(os.path.dirname(SUMMARY_PATH) or ".", exist_ok=True)
    lines = [
        "# Experiment B2 — Float64 High-Curvature Probe Results\n",
        "",
        "| Run ID | K value | Final PPL | Stability | Note |",
        "|--------|---------|-----------|-----------|------|",
    ]
    for r in results:
        ppl_str  = f"{r['final_ppl']:.1f}" if r["final_ppl"] is not None else "N/A"
        note     = r.get("note", "—")
        lines.append(
            f"| {r['run_id']} | {r['K']} | {ppl_str} | {r['stability']} | {note} |"
        )
    lines.append("")
    lines.append(f"B k10 baseline: {B_K10_BASELINE_PPL} PPL  ")
    lines.append("")
    lines.append("_Generated by sweep_b2.py_")
    with open(SUMMARY_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Summary written → {SUMMARY_PATH}")


# ---------------------------------------------------------------------------
# Main sweep
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Experiment B2 float64 sweep")
    parser.add_argument("--all",   action="store_true",
                        help="Also run k100 (ceiling probe)")
    parser.add_argument("--force", action="store_true",
                        help="Skip replication check warning for b2_k10")
    args = parser.parse_args()

    sweep = SWEEP_ALL if args.all else SWEEP_BASE

    results       = []
    stopped_early = False
    stop_reason   = ""
    prev_ppl      = None
    prev_K        = None

    print("=" * 60)
    print("Experiment B2 — Float64 Curvature Sweep")
    print(f"  Replication baseline: B k10 = {B_K10_BASELINE_PPL} PPL")
    print(f"  Degradation threshold: {DEGRADATION_TOL_PPL} PPL")
    print("=" * 60)

    for run_id, config_path, K_val in sweep:
        if stopped_early:
            print(f"\n[SKIP] {run_id} (K={K_val}) — {stop_reason}")
            results.append({
                "run_id": run_id, "K": K_val, "final_ppl": None,
                "stability": "SKIPPED", "note": stop_reason,
            })
            continue

        print(f"\n{'=' * 60}")
        print(f"[RUN] {run_id}  K={K_val}  config={config_path}")
        print("=" * 60)

        subprocess.run(
            [sys.executable, "scripts/train.py", "--config", config_path],
            cwd=os.getcwd(),
        )

        try:
            classification, div_step = _detect_divergence(run_id)
        except (FileNotFoundError, RuntimeError) as exc:
            print(f"\n[ERROR] Could not read results for {run_id}:")
            print(f"  {exc}")
            raise

        final_ppl = _get_final_ppl(run_id)
        note = "—"
        print(f"\n[RESULT] {run_id}: stability={classification}, "
              f"final_ppl={final_ppl}, divergence_step={div_step}")

        # ------------------------------------------------------------------
        # Replication check (b2_k10 only)
        # ------------------------------------------------------------------
        if run_id == "exp_b2_k10" and final_ppl is not None:
            diff = abs(final_ppl - B_K10_BASELINE_PPL)
            if diff > REPLICATION_TOL_PPL:
                msg = (
                    f"[WARN] b2_k10 PPL={final_ppl:.1f} differs from B k10 "
                    f"baseline ({B_K10_BASELINE_PPL}) by {diff:.1f} PPL.\n"
                    f"       Investigate before continuing sweep. "
                    f"Re-run with --force to override."
                )
                print(msg)
                note = f"replication_diff={diff:.1f}"
                if not args.force:
                    results.append({
                        "run_id": run_id, "K": K_val, "final_ppl": final_ppl,
                        "stability": classification, "note": note,
                    })
                    _write_summary(results)
                    print("\n[STOP] Sweep paused at replication check. "
                          "Fix the issue or re-run with --force.")
                    sys.exit(1)
            else:
                note = f"replication_diff={diff:.1f} (OK)"
                print(f"[OK] Replication check passed: diff={diff:.1f} PPL")

        # ------------------------------------------------------------------
        # Degradation check (all runs after the first)
        # ------------------------------------------------------------------
        if prev_ppl is not None and final_ppl is not None:
            degradation = final_ppl - prev_ppl
            if degradation > DEGRADATION_TOL_PPL:
                stopped_early = True
                stop_reason = (
                    f"PPL degraded from {prev_ppl:.1f} to {final_ppl:.1f} "
                    f"at K={K_val}"
                )
                print(
                    f"\n[STOP] {stop_reason}.\n"
                    f"       Optimum is likely near K={prev_K}."
                )
                note = f"degradation={degradation:.1f} (STOP)"

        # ------------------------------------------------------------------
        # Divergence check
        # ------------------------------------------------------------------
        if classification == "DIVERGED":
            stopped_early = True
            stop_reason   = f"{run_id} (K={K_val}) diverged at step {div_step}"
            print("[STOP] Divergence detected — skipping remaining runs.")

        results.append({
            "run_id": run_id, "K": K_val, "final_ppl": final_ppl,
            "stability": classification, "note": note,
        })
        prev_ppl = final_ppl
        prev_K   = K_val

    _write_summary(results)

    plot_script = "scripts/plot_b2.py"
    if os.path.exists(plot_script):
        print(f"\n[PLOT] Running {plot_script} ...")
        subprocess.run([sys.executable, plot_script])
    else:
        print(f"[WARN] {plot_script} not found — skipping plots.")

    print("\n[DONE] Sweep complete.")
    for r in results:
        ppl_str = f"{r['final_ppl']:.1f}" if r["final_ppl"] else "N/A"
        print(f"  {r['run_id']:12s}  K={r['K']:7.1f}  PPL={ppl_str:>8s}  "
              f"{r['stability']}")


if __name__ == "__main__":
    main()
