"""
sweep_curvature.py — Sequential curvature sweep for Experiment B
=================================================================

Runs all curvature configs in order (k1 → k2 → k5 → k10 → k50).
If a run diverges (NaN loss), skips remaining higher-curvature runs.
After all runs, calls plot_curvature_sweep.py automatically.

Usage:
    cd ~/hyper-attn-nano
    source activate.sh
    python scripts/sweep_curvature.py
    python scripts/sweep_curvature.py --skip-k50
"""

import argparse
import json
import math
import os
import subprocess
import sys

SWEEP_ORDER = [
    ("exp_b_k1",  "configs/nano_hyper_fixed_k1.yaml",  -1.0),
    ("exp_b_k2",  "configs/nano_hyper_fixed_k2.yaml",  -2.0),
    ("exp_b_k5",  "configs/nano_hyper_fixed_k5.yaml",  -5.0),
    ("exp_b_k10", "configs/nano_hyper_fixed_k10.yaml", -10.0),
    ("exp_b_k50", "configs/nano_hyper_fixed_k50.yaml", -50.0),
]

SUMMARY_PATH    = "results/exp_b_summary.md"
RESULTS_LOG_DIR = "results/logs/exp_b"


def _detect_divergence(run_id):
    log_path = os.path.join(RESULTS_LOG_DIR, f"{run_id}_train.jsonl")
    if not os.path.exists(log_path):
        raise FileNotFoundError(
            f"Log file not found: {log_path}\n"
            f"  Expected the training script to write to this path.\n"
            f"  Check that the config's run_id matches '{run_id}' "
            f"and that train.py completed without error."
        )

    records = []
    with open(log_path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    pass

    if not records:
        raise RuntimeError(
            f"Log file exists but contains no valid records: {log_path}\n"
            f"  The training run may have crashed before the first eval step."
        )

    div_step = None
    for rec in records:
        ppl = rec.get("val_ppl", float("inf"))
        if not math.isfinite(ppl) or ppl > 1e6:
            if div_step is None:
                div_step = rec["step"]

    final_rec   = records[-1]
    final_step  = final_rec["step"]
    final_grad  = final_rec.get("grad_norm", 0.0)

    if div_step is not None and div_step >= final_step:
        return "DIVERGED", div_step
    elif div_step is not None:
        return "DEGRADED", div_step
    else:
        return "STABLE", None


def _get_final_ppl(run_id):
    log_path = os.path.join(RESULTS_LOG_DIR, f"{run_id}_train.jsonl")
    if not os.path.exists(log_path):
        return None
    records = []
    with open(log_path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    for rec in reversed(records):
        ppl = rec.get("val_ppl")
        if ppl is not None and math.isfinite(ppl):
            return ppl
    return None


def _write_summary(results):
    os.makedirs(os.path.dirname(SUMMARY_PATH) or ".", exist_ok=True)
    lines = [
        "# Experiment B — Curvature Sweep Results\n",
        "",
        "| Run ID | K value | Final PPL | Stability | Divergence Step |",
        "|--------|---------|-----------|-----------|-----------------|",
    ]
    for r in results:
        ppl_str = f"{r['final_ppl']:.1f}" if r["final_ppl"] is not None else "N/A"
        div_str = str(r["divergence_step"]) if r["divergence_step"] is not None else "—"
        lines.append(
            f"| {r['run_id']} | {r['K']} | {ppl_str} | {r['stability']} | {div_str} |"
        )
    lines.append("")
    lines.append("_Generated by sweep_curvature.py_")
    with open(SUMMARY_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Summary written → {SUMMARY_PATH}")


def main():
    parser = argparse.ArgumentParser(description="Experiment B curvature sweep")
    parser.add_argument("--skip-k50", action="store_true",
                        help="Skip the K=-50 ceiling-probe run")
    args = parser.parse_args()

    sweep = SWEEP_ORDER if not args.skip_k50 else SWEEP_ORDER[:-1]

    results       = []
    stopped_early = False
    stop_reason   = ""

    print("=" * 60)
    print("Experiment B — Curvature Sweep")
    print("=" * 60)

    for run_id, config_path, K_val in sweep:
        if stopped_early:
            print(f"\n[SKIP] {run_id} (K={K_val}) — {stop_reason}")
            results.append({"run_id": run_id, "K": K_val, "final_ppl": None,
                            "stability": "SKIPPED", "divergence_step": None})
            continue

        print(f"\n{'=' * 60}")
        print(f"[RUN] {run_id}  K={K_val}  config={config_path}")
        print("=" * 60)

        subprocess.run([sys.executable, "scripts/train.py", "--config", config_path],
                       cwd=os.getcwd())

        try:
            classification, div_step = _detect_divergence(run_id)
        except (FileNotFoundError, RuntimeError) as exc:
            print(f"\n[ERROR] Could not read results for {run_id}:")
            print(f"  {exc}")
            raise
        final_ppl = _get_final_ppl(run_id)

        print(f"\n[RESULT] {run_id}: stability={classification}, "
              f"final_ppl={final_ppl}, divergence_step={div_step}")

        results.append({"run_id": run_id, "K": K_val, "final_ppl": final_ppl,
                        "stability": classification, "divergence_step": div_step})

        if classification == "DIVERGED":
            stopped_early = True
            stop_reason   = f"{run_id} (K={K_val}) diverged at step {div_step}"
            print("[STOP] Divergence detected — skipping remaining higher-curvature runs.")

    _write_summary(results)

    plot_script = "scripts/plot_curvature_sweep.py"
    if os.path.exists(plot_script):
        print(f"\n[PLOT] Running {plot_script} ...")
        subprocess.run([sys.executable, plot_script])
    else:
        print(f"[WARN] {plot_script} not found — skipping plots.")

    print("\n[DONE] Sweep complete.")
    for r in results:
        ppl_str = f"{r['final_ppl']:.1f}" if r["final_ppl"] else "N/A"
        print(f"  {r['run_id']:6s}  K={r['K']:6.1f}  PPL={ppl_str:>10s}  {r['stability']}")


if __name__ == "__main__":
    main()
